Repository vansh-codes/Gityzer, pull requests merged in 2024-10, with the labels that each got.

#9 Autocomment workflow issue fix
  .github/workflows/autocomment-iss-close.yml
Labels: hacktoberfest, hacktoberfest-accepted

#13 Fixed the workflow issue #10
  .github/workflows/autocomment-iss-close.yml
Labels: documentation, good first issue, gssoc-ext, level1, hacktoberfest, hacktoberfest-accepted

#14 fix: 🐛 Enhanced README with contributors section
  .github/workflows/add-contributors.yml
  CONTRIBUTORS.md
  README.md
Labels: documentation, enhancement, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#17 Update the branch master name in action workflow
  .github/workflows/add-contributors.yml
  CONTRIBUTORS.md
Labels: bug

#25 resolved mobile responsiveness
  .gitignore
  components/Home.jsx
Labels: enhancement, gssoc-ext, level1, hacktoberfest, hacktoberfest-accepted, frontend

#22 issue 19 resolved. tagline generation using gemini successfully added.
  ai/generateTagline.js
  package-lock.json
  package.json
  src/app/[username]/page.jsx
  src/app/api/ai/route.js
Labels: enhancement, AI, gssoc-ext, level3, hacktoberfest, hacktoberfest-accepted, frontend

#30 Tagline Generation resolved
  ai/generateTagline.js
  src/app/api/ai/route.js
  src/app/page.jsx
Labels: bug, AI, gssoc-ext, level1, hacktoberfest, hacktoberfest-accepted

#36 fixed ai issue
  .env.example
  ai/generateTagline.js
  components/Home.jsx
  package-lock.json
  package.json
  src/app/[username]/page.jsx
  src/app/api/ai/route.js
Labels: changes requested

#46 Implement GitHub PR Issue Checker Workflow
  .github/workflows/pr-checker.yaml
Labels: documentation, gssoc-ext, level1, hacktoberfest-accepted

#54 Create error 404 page not found
  package-lock.json
  src/app/[username]/page.jsx
  src/app/images/Githuberror404.png
  src/app/not-found.jsx
Labels: enhancement, gssoc-ext, level2, hacktoberfest-accepted

#53 issue #52: Added most used language in generating tagline
  ai/generateTagline.js
  src/app/api/ai/route.js
Labels: AI, gssoc-ext, level1

#59 🚀Added Github Userdata Fetching using Github Ofiicial Api
  next.config.mjs
  package-lock.json
  package.json
  src/app/[username]/page.jsx
  src/app/api/user/route.js
Labels: enhancement, gssoc-ext, level2, hacktoberfest-accepted

#62 Feat:Animated Tagline
  components/Home.jsx
  package-lock.json
  package.json
Labels: enhancement, gssoc-ext, level1, frontend

#70 Header, home icon, redirects to home page
  components/Home.jsx
  src/app/[username]/page.jsx
Labels: enhancement, gssoc-ext, level1

#73 Automation of project structure updation using GitHub workflows and Python scripts
  .github/scripts/update_structure.py
  .github/workflows/update-readme.yml
  PROJECT_STRUCTURE.md
  README.md
  repo_structure.txt
Labels: documentation, enhancement, gssoc-ext, level1, hacktoberfest-accepted
