Repository vansh-codes/Gityzer, pull requests merged in 2024-11, with the labels that each got.

#80 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation, gssoc-ext, level1

#88 Added download button for exporting stats of repo in txt format
  src/app/[username]/page.jsx
Labels: enhancement, gssoc-ext, level2, frontend

#91 Feature: Added download profile stats
  src/app/[username]/page.jsx
Labels: enhancement, gssoc-ext, level1, frontend

#92 Added a recents search feature
  components/Home.jsx
Labels: enhancement, gssoc-ext, level2, frontend

#94 Added a navigation button to profile Page
  src/app/[username]/page.jsx
Labels: enhancement, frontend
